"""create schema

Revision ID: 17c9c935717e
Revises: 
Create Date: 2023-05-21 22:51:10.603996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17c9c935717e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('UUID', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('UUID')
    )
    op.create_table('record',
    sa.Column('record_id', sa.Integer(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('UUID', sa.UUID(), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=False),
    sa.Column('record_name', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('record_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('record')
    op.drop_table('user')
    # ### end Alembic commands ###
