version: '1'

volumes:  # set the volume with name postgres_volume
  postgres_volume:

services:
  postgres:
    image: postgres:15.3-alpine  # here is no any reason to use debian version
    container_name: postgres_server_test2
    volumes:
      - postgres_volume:/var/lib/postgresql/data  # default location according to https://hub.docker.com/_/postgres
    restart: always
    ports:
      - "5431:5432"  # run app on local port 5431, postgres in container on port 5432
    environment:  # import from .env
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
